services:
  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rails
    ports:
      - "5432:5432"

  pgbouncer:
    image: bitnami/pgbouncer:1.23.1
    restart: always
    depends_on:
      - db
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT_NUMBER=5432
      - POSTGRESQL_DATABASE=rails
      - PGBOUNCER_DEFAULT_POOL_SIZE=30
      - PGBOUNCER_DATABASE=rails
    ports:
      - "6432:6432"

  k6:
    image: grafana/k6:0.52.0
